import type { Task } from "@/types";

export const mockTasks: Task[] = [
  {
    id: "task_1",
    boardId: "board_1",
    title: "Define MVP scope",
    description: "Outline core features for the initial release",
    status: "done",
    priority: "high",
    assigneeId: "user_1",
    createdAt: "2025-04-02T10:00:00.000Z",
  },
  {
    id: "task_2",
    boardId: "board_1",
    title: "Design landing page",
    description: "Create wireframes and mockups for the landing page",
    status: "review",
    priority: "medium",
    assigneeId: "user_2",
    createdAt: "2025-04-05T10:00:00.000Z",
  },
  {
    id: "task_3",
    boardId: "board_1",
    title: "Implement auth flow",
    description: "Login, register, and password reset pages",
    status: "in_progress",
    priority: "high",
    assigneeId: "user_3",
    createdAt: "2025-04-08T10:00:00.000Z",
  },
  {
    id: "task_4",
    boardId: "board_1",
    title: "Set up CI/CD pipeline",
    description: "Configure GitHub Actions for automated deployments",
    status: "todo",
    priority: "medium",
    assigneeId: "user_1",
    createdAt: "2025-04-10T10:00:00.000Z",
  },
  {
    id: "task_5",
    boardId: "board_1",
    title: "Write API documentation",
    description: "Document all REST endpoints with examples",
    status: "todo",
    priority: "low",
    assigneeId: "user_2",
    createdAt: "2025-04-12T10:00:00.000Z",
  },
  {
    id: "task_6",
    boardId: "board_1",
    title: "User research interviews",
    description: "Conduct 5 user interviews for feedback",
    status: "backlog",
    priority: "medium",
    assigneeId: "user_3",
    createdAt: "2025-04-15T10:00:00.000Z",
  },
  {
    id: "task_7",
    boardId: "board_1",
    title: "Performance audit",
    description: "Run Lighthouse and optimize Core Web Vitals",
    status: "backlog",
    priority: "low",
    createdAt: "2025-04-18T10:00:00.000Z",
  },
  {
    id: "task_8",
    boardId: "board_1",
    title: "Integrate analytics",
    description: "Set up event tracking and dashboards",
    status: "in_progress",
    priority: "medium",
    assigneeId: "user_2",
    createdAt: "2025-04-20T10:00:00.000Z",
  },
  {
    id: "task_9",
    boardId: "board_2",
    title: "Create social media calendar",
    description: "Plan posts for the next 4 weeks",
    status: "todo",
    priority: "high",
    assigneeId: "user_1",
    createdAt: "2025-05-05T10:00:00.000Z",
  },
  {
    id: "task_10",
    boardId: "board_2",
    title: "Design email templates",
    description: "Newsletter and promotional email designs",
    status: "in_progress",
    priority: "medium",
    assigneeId: "user_2",
    createdAt: "2025-05-08T10:00:00.000Z",
  },
  {
    id: "task_11",
    boardId: "board_2",
    title: "Budget allocation",
    description: "Split budget across channels",
    status: "backlog",
    priority: "high",
    assigneeId: "user_1",
    createdAt: "2025-05-10T10:00:00.000Z",
  },
  {
    id: "task_12",
    boardId: "board_2",
    title: "Influencer outreach",
    description: "Contact 10 micro-influencers",
    status: "review",
    priority: "medium",
    assigneeId: "user_2",
    createdAt: "2025-05-12T10:00:00.000Z",
  },
  {
    id: "task_13",
    boardId: "board_2",
    title: "A/B test ad copy",
    description: "Run split tests on ad headlines",
    status: "done",
    priority: "low",
    assigneeId: "user_1",
    createdAt: "2025-05-15T10:00:00.000Z",
  },
  {
    id: "task_14",
    boardId: "board_1",
    title: "Security review",
    description: "Review auth and data access patterns",
    status: "review",
    priority: "high",
    assigneeId: "user_1",
    createdAt: "2025-05-20T10:00:00.000Z",
  },
  {
    id: "task_15",
    boardId: "board_1",
    title: "Onboarding flow",
    description: "Design first-time user experience",
    status: "backlog",
    priority: "medium",
    assigneeId: "user_3",
    createdAt: "2025-05-22T10:00:00.000Z",
  },
];
