import type { TelegramDraftTask } from "@/types";

export const mockTelegramDrafts: TelegramDraftTask[] = [
  {
    id: "tg_1",
    title: "Fix login bug on mobile",
    description: "Users report login fails on iOS Safari",
    priority: "high",
    senderName: "Mike",
    senderUsername: "@mike_dev",
    receivedAt: "2025-06-17T09:00:00.000Z",
    status: "pending",
  },
  {
    id: "tg_2",
    title: "Update pricing page",
    description: "New Pro plan pricing needs to be reflected",
    priority: "medium",
    senderName: "Sarah",
    senderUsername: "@sarah_pm",
    receivedAt: "2025-06-17T10:30:00.000Z",
    status: "pending",
  },
  {
    id: "tg_3",
    title: "Add dark mode toggle",
    description: "Feature request from Discord community",
    priority: "low",
    senderName: "Chris",
    senderUsername: "@chris_ux",
    receivedAt: "2025-06-17T11:15:00.000Z",
    status: "pending",
  },
  {
    id: "tg_4",
    title: "Deploy hotfix v1.2.1",
    description: "Critical patch for payment webhook",
    priority: "high",
    senderName: "Alex",
    senderUsername: "@alex_ops",
    receivedAt: "2025-06-17T14:00:00.000Z",
    status: "pending",
  },
  {
    id: "tg_5",
    title: "Write release notes",
    description: "Document changes for v1.2.0 release",
    priority: "medium",
    senderName: "Emma",
    senderUsername: "@emma_docs",
    receivedAt: "2025-06-17T15:45:00.000Z",
    status: "pending",
  },
];
